/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelproject;

import javax.swing.JOptionPane;

/**
 *
 * @author administrador_julian
 */
public class Precios extends javax.swing.JFrame {

    /**
     * Creates new form Precios
     */
    public Precios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InfoEstandar1 = new javax.swing.JButton();
        InfoPremium1 = new javax.swing.JButton();
        InfoSuite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VolverMenu.setBackground(new java.awt.Color(0, 153, 255));
        VolverMenu.setText("Regresar");
        VolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(VolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Precios.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 470));

        InfoEstandar1.setText("Info");
        InfoEstandar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoEstandar1ActionPerformed(evt);
            }
        });
        getContentPane().add(InfoEstandar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 90, 20));

        InfoPremium1.setText("Info");
        InfoPremium1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoPremium1ActionPerformed(evt);
            }
        });
        getContentPane().add(InfoPremium1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 90, 20));

        InfoSuite.setText("Info");
        InfoSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoSuiteActionPerformed(evt);
            }
        });
        getContentPane().add(InfoSuite, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoEstandar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoEstandar1ActionPerformed
        JOptionPane.showMessageDialog(null, "<html><body><div style='width: 300px;'>"
                + "<h2 style='color: #007bff; text-align: center;'>¡Bienvenido a nuestra habitación doble estándar!</h2>"
                + "<p style='text-align: justify;'>Esta habitación es el lugar perfecto para aquellos que buscan comodidad y practicidad a un precio accesible. Por solo COP 207.000, puedes alojarte hasta con 4 personas.</p>"
                + "<p style='text-align: justify;'>El diseño interior es sencillo pero acogedor, con muebles funcionales y una distribución que aprovecha al máximo el espacio disponible.</p>"
                + "<p style='text-align: justify;'>Aquí encontrarás todas las comodidades básicas necesarias para garantizar una estancia confortable, desde camas confortables hasta ropa de cama limpia y toallas frescas.</p>"
                + "<p style='text-align: justify;'>Aunque no se incluye el desayuno ni servicio a la habitación, no te preocupes, ¡hay muchas opciones cercanas para disfrutar de la deliciosa gastronomía local!</p>"
                + "<p style='text-align: justify;'>Además, esta habitación te brinda la privacidad y tranquilidad que necesitas, ideal para relajarte después de un día de exploración o trabajo.</p>"
                + "</div></body></html>", "Información de la Habitación", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_InfoEstandar1ActionPerformed

    private void InfoPremium1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoPremium1ActionPerformed
        JOptionPane.showMessageDialog(null, "<html><body><div style='width: 300px;'>"
                + "<h2 style='color: #8B008B; text-align: center;'>¡Bienvenido a nuestra lujosa habitación Premium!</h2>"
                + "<p style='text-align: justify;'>Disfruta de una experiencia de alojamiento excepcional en nuestra habitación Premium, diseñada para satisfacer hasta 4 personas por solo COP 378.893. Aquí encontrarás una amplia gama de comodidades exclusivas que garantizan una estancia indulgente y confortable.</p>"
                + "<p style='text-align: justify;'>Una de las características destacadas de esta habitación es su jacuzzi privado, donde podrás relajarte y rejuvenecer después de un día lleno de actividades. Además, se incluye un delicioso desayuno que seguramente satisfará tu paladar y te dará la energía necesaria para comenzar el día con el pie derecho.</p>"
                + "<p style='text-align: justify;'>Para añadir un toque adicional de conveniencia y lujo, ofrecemos servicio a la habitación, permitiéndote disfrutar de comida y bebida de alta calidad en la comodidad de tu propio espacio. Ya sea que desees un bocado ligero o una cena completa, nuestro servicio está disponible para atender todas tus necesidades con elegancia y atención al detalle.</p>"
                + "</div></body></html>", "Información de la Habitación Premium", JOptionPane.INFORMATION_MESSAGE);        
    
    }//GEN-LAST:event_InfoPremium1ActionPerformed

    private void InfoSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoSuiteActionPerformed
        JOptionPane.showMessageDialog(null, "<html><body><div style='width: 300px;'>"
                + "<h2 style='color: #FFA500; text-align: center;'>¡Bienvenido a nuestra lujosa suite!</h2>"
                + "<p style='text-align: justify;'>Esta suite está diseñada para satisfacer hasta 6 personas, ofreciendo una experiencia de alojamiento excepcional por COP 631.546. Es el refugio perfecto para aquellos que buscan una estancia inolvidable y llena de comodidades.</p>"
                + "<p style='text-align: justify;'>En el corazón de esta suite se encuentra un exquisito jacuzzi, donde puedes sumergirte y relajarte mientras disfrutas de la tranquilidad y el confort. Además, la suite cuenta con una espaciosa sala de estar, perfecta para reunirse con amigos o familiares y crear recuerdos inolvidables juntos.</p>"
                + "<p style='text-align: justify;'>Disfruta de la privacidad y comodidad de un baño privado, equipado con todas las comodidades necesarias para tu confort. La suite también cuenta con una lujosa cama king-size, garantizando un descanso reparador y placentero.</p>"
                + "<p style='text-align: justify;'>Déjate cautivar por las vistas desde el balcón privado, donde puedes disfrutar de momentos de tranquilidad y contemplación mientras admiras el entorno circundante.</p>"
                + "<p style='text-align: justify;'>Para comenzar el día de la mejor manera posible, se incluye un delicioso desayuno que seguramente satisfará todos tus antojos y te brindará la energía necesaria para tus aventuras diarias.</p>"
                + "<p style='text-align: justify;'>Además, para una experiencia aún más indulgente, el servicio a la habitación está disponible para atender todas tus necesidades culinarias con elegancia y estilo.</p>"
                + "</div></body></html>", "Información de la Suite", JOptionPane.INFORMATION_MESSAGE);        
               
    }//GEN-LAST:event_InfoSuiteActionPerformed

    private void VolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuActionPerformed
        Hotel hotel = new Hotel();
        this.setVisible(false);
        hotel.setVisible(true);
    }//GEN-LAST:event_VolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Precios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoEstandar1;
    private javax.swing.JButton InfoPremium1;
    private javax.swing.JButton InfoSuite;
    private javax.swing.JButton VolverMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
